dist: trusty
language: node_js
node_js:
- stable
branches:
  only: development
notifications:
  email:
    recipients:
    - joexu1997@gmail.com      # change to your own address
    on_success: never        # default: change
    on_failure: always       # default: always
